services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "100.73.160.84:8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      # se ti serve anche qui (opzionale)
      - ./mosquitto/certs:/app/certs:ro

  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    # PROD: accesso solo locale host
    ports:
      - "127.0.0.1:8086:8086"
    env_file:
      - .env
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2

  control-room-api:
    image: ghcr.io/filippoctass-debug/control-room-api:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - "100.73.160.84:8000:8000"
    volumes:
      - ./mosquitto/certs:/mosquitto/certs:ro
      - ./fastapi/app/mqtt_ingest.py:/app/app/mqtt_ingest.py:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

   watchtower-cloud:
    image: containrrr/watchtower:1.7.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
      - REPO_USER=${GHCR_USER}
      - REPO_PASS=${GHCR_TOKEN}
    command: --interval 60 --cleanup --label-enable --registry-auth
