# === AUTH ===
allow_anonymous false
password_file /mosquitto/config/passwords.txt

# === TLS listener interno docker ===
listener 8883
protocol mqtt

cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key

# Non richiedere certificato client (usiamo user/pass)
require_certificate false
use_identity_as_username false

# (opzionale ma consigliato)
tls_version tlsv1.2

# ACL (se le usi)
# acl_file /mosquitto/config/acl
