services:
  edge-driver:
    build: .
    image: edge-driver:local
    restart: always
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./certs:/certs:ro
      - ./data:/app/data

  watchtower:
    image: containrrr/watchtower:1.7.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --label-enable
      --interval 30
      --cleanup
