services:
  edge-driver:
    build: .
    image: edge-edge-driver
    container_name: edge-driver
    restart: unless-stopped
    user: "0:0"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs:ro


  watchtower-edge:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower-edge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
